// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-C-stmkutkMd4uyk4BK7WD5EjwJZvZcI',
    appId: '1:56570663770:web:427691b533ca4c87f65963',
    messagingSenderId: '56570663770',
    projectId: 'servant-management',
    authDomain: 'servant-management.firebaseapp.com',
    storageBucket: 'servant-management.appspot.com',
    measurementId: 'G-MXCQE6Q0EX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB-bNDlrp_DYM62Ty5Ho8InYRHUW5vFZ6w',
    appId: '1:56570663770:android:1a9207cd67be3250f65963',
    messagingSenderId: '56570663770',
    projectId: 'servant-management',
    storageBucket: 'servant-management.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0R46Si-cg-uBADqauDui74rmbcLAFMwE',
    appId: '1:56570663770:ios:9a62d2b36b16b355f65963',
    messagingSenderId: '56570663770',
    projectId: 'servant-management',
    storageBucket: 'servant-management.appspot.com',
    iosBundleId: 'com.example.servantmanagement',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB0R46Si-cg-uBADqauDui74rmbcLAFMwE',
    appId: '1:56570663770:ios:cde46188258b778bf65963',
    messagingSenderId: '56570663770',
    projectId: 'servant-management',
    storageBucket: 'servant-management.appspot.com',
    iosBundleId: 'com.example.servantmanagement.RunnerTests',
  );
}
